import CardGroup from "./CardGroup";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";

const emptyResp = {
  page: {
    pageNumber: 0,
    pageSize: 50,
    numberOfElements: 0,
    totalElements: 0,
    totalPages: 0,
    firstPage: true,
    lastPage: true,
  },
  sort: {
    clauses: [],
  },
  characters: [],
};

const respWith13Characters = {
  page: {
    pageNumber: 0,
    pageSize: 50,
    numberOfElements: 0,
    totalElements: 0,
    totalPages: 0,
    firstPage: true,
    lastPage: true,
  },
  sort: {
    clauses: [],
  },
  characters: [
    {
      uid: "CHMA0000215045",
      name: "0413 Theta",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: true,
      alternateReality: false,
    },
    {
      uid: "CHMA0000174718",
      name: "0718",
      gender: "M",
      yearOfBirth: 2259,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: true,
    },
    {
      uid: "CHMA0000283851",
      name: "10111",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
    {
      uid: "CHMA0000278055",
      name: "335",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
    {
      uid: "CHMA0000282741",
      name: "355",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
    {
      uid: "CHMA0000026532",
      name: "A'trom",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
    {
      uid: "CHMA0000280385",
      name: "A. Armaganian",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
    {
      uid: "CHMA0000226457",
      name: "A. Baiers",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
    {
      uid: "CHMA0000232390",
      name: "A. Baiers",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: true,
      alternateReality: false,
    },
    {
      uid: "CHMA0000068580",
      name: "A. Banda",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
    {
      uid: "CHMA0000053843",
      name: "A. Bormanis",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
    {
      uid: "CHMA0000069222",
      name: "A. Bro",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
    {
      uid: "CHMA0000280434",
      name: "A. Brock",
      gender: null,
      yearOfBirth: null,
      monthOfBirth: null,
      dayOfBirth: null,
      placeOfBirth: null,
      yearOfDeath: null,
      monthOfDeath: null,
      dayOfDeath: null,
      placeOfDeath: null,
      height: null,
      weight: null,
      deceased: null,
      bloodType: null,
      maritalStatus: null,
      serialNumber: null,
      hologramActivationDate: null,
      hologramStatus: null,
      hologramDateStatus: null,
      hologram: false,
      fictionalCharacter: false,
      mirror: false,
      alternateReality: false,
    },
  ],
};

describe("Card Group tests", () => {
  it("appropriate message is displayed if no cards are present", () => {
    render(
      <MemoryRouter>
        <CardGroup searchedElements={emptyResp}></CardGroup>
      </MemoryRouter>,
    );
    const notFoundMessage = screen.getByText(/isn't any character/);
    expect(notFoundMessage).toBeInTheDocument();
  });

  it("component renders 13 cards, when array of 13 characters is passed", () => {
    render(
      <MemoryRouter initialEntries={["/?page=1"]}>
        <CardGroup searchedElements={respWith13Characters}></CardGroup>
      </MemoryRouter>,
    );
    render(
      <MemoryRouter initialEntries={["/?page=2"]}>
        <CardGroup searchedElements={respWith13Characters}></CardGroup>
      </MemoryRouter>,
    );

    const quiredElements = screen.getAllByRole("listitem");
    expect(quiredElements).toHaveLength(13);
  });
});
